Lectura de datos

In [ ]:
import pandas as pd
from pandas import DataFrame

Ej=pd.read_csv('Country2.csv', index_col='Code', nrows=20)
Ej=Ej.drop(['SurfaceArea','LifeExpectancy','Continent','Region','LocalName','GovernmentForm','Capital'], axis=1)
print(Ej)

                             Name  IndepYear  Population       GNP    GNPOld
Code
ABW                         Aruba        NaN      103000     828.0     793.0
AFG                   Afghanistan     1919.0    22720000    5976.0       NaN
AGO                        Angola     1975.0    12878000    6648.0    7984.0
AIA                           NaN        NaN        8000      63.2       NaN
ALB                           NaN     1912.0     3401200    3205.0    2500.0
AND                       Andorra     1278.0           0    1630.0       NaN
ANT          Netherlands Antilles        NaN      217000    1941.0       NaN
ARE          United Arab Emirates     1971.0     2441000       0.0   36846.0
ARG                     Argentina     1816.0    37032000  340238.0  323310.0
ARM                       Armenia     1991.0     3520000    1813.0    1627.0
ASM                American Samoa        NaN       68000     334.0       NaN
ATA                    Antarctica        NaN           0       0.0       NaN
ATF   French Southern territories        NaN           0       0.0       NaN
ATG           Antigua and Barbuda     1981.0       68000     612.0     584.0
AUS                     Australia     1901.0           0  351182.0  392911.0
AUT                       Austria     1918.0     8091800       0.0  206025.0
AZE                    Azerbaijan     1991.0     7734000    4127.0    4100.0
BDI                       Burundi     1962.0     6695000     903.0     982.0
BEL                       Belgium     1830.0    10239000  249704.0  243948.0
BEN                         Benin     1960.0     6097000    2357.0    2141.0

#Datos faltantes
Se les llama "Datos faltantes" a aquellas "celdas" que no tienen datos o tienen un dato nulo (celda vacía o valor nan).

##Filtrado
Para detectar los datos faltantes, se tienen dos funciones que retornan uns serie de valores lógicos:

`isnull()`: Retorna un True si el dato es nulo y False en caso de que tenga un valor asignado

`notnull()`: Retorna False si es un dato nulo y True si tiene un valor asignado

In [ ]:
print(Ej.isnull())

       Name  IndepYear  Population    GNP  GNPOld
Code
ABW   False       True       False  False   False
AFG   False      False       False  False    True
AGO   False      False       False  False   False
AIA    True       True       False  False    True
ALB    True      False       False  False   False
AND   False      False       False  False    True
ANT   False       True       False  False    True
ARE   False      False       False  False   False
ARG   False      False       False  False   False
ARM   False      False       False  False   False
ASM   False       True       False  False    True
ATA   False       True       False  False    True
ATF   False       True       False  False    True
ATG   False      False       False  False   False
AUS   False      False       False  False   False
AUT   False      False       False  False   False
AZE   False      False       False  False   False
BDI   False      False       False  False   False
BEL   False      False       False  False   False
BEN   False      False       False  False   False

In [ ]:
print(len(Ej)-Ej.count())

Name          2
IndepYear     6
Population    0
GNP           0
GNPOld        7
dtype: int64

##Eliminar datos nulos
`dropna()` retorna una columna o un frame sin los datos nulos. En caso de que se aplique a todo el frame, eliminará una fila si hay por lo menos una columna por un nulo.

**NO ES LO MISMO UN DATO NULO QUE UN 0**

In [ ]:
Ej.dropna()

                      Name  IndepYear  Population       GNP    GNPOld
Code
AGO                 Angola     1975.0    12878000    6648.0    7984.0
ARE   United Arab Emirates     1971.0     2441000       0.0   36846.0
ARG              Argentina     1816.0    37032000  340238.0  323310.0
ARM                Armenia     1991.0     3520000    1813.0    1627.0
ATG    Antigua and Barbuda     1981.0       68000     612.0     584.0
AUS              Australia     1901.0           0  351182.0  392911.0
AUT                Austria     1918.0     8091800       0.0  206025.0
AZE             Azerbaijan     1991.0     7734000    4127.0    4100.0
BDI                Burundi     1962.0     6695000     903.0     982.0
BEL                Belgium     1830.0    10239000  249704.0  243948.0
BEN                  Benin     1960.0     6097000    2357.0    2141.0

In [ ]:
Ej['GNPOld'].dropna()

Code
ABW       793.0
AGO      7984.0
ALB      2500.0
ARE     36846.0
ARG    323310.0
ARM      1627.0
ATG       584.0
AUS    392911.0
AUT    206025.0
AZE      4100.0
BDI       982.0
BEL    243948.0
BEN      2141.0
Name: GNPOld, dtype: float64

In [ ]:
print("Sin datos nulos en la columna GNPOld y Name:\n",Ej[['GNPOld','Name']].dropna())

Sin datos nulos en la columna GNPOld y Name:
         GNPOld                  Name
Code
ABW      793.0                 Aruba
AGO     7984.0                Angola
ARE    36846.0  United Arab Emirates
ARG   323310.0             Argentina
ARM     1627.0               Armenia
ATG      584.0   Antigua and Barbuda
AUS   392911.0             Australia
AUT   206025.0               Austria
AZE     4100.0            Azerbaijan
BDI      982.0               Burundi
BEL   243948.0               Belgium
BEN     2141.0                 Benin

In [ ]:
print("Numero de elementos nulos (IndepYear):",Ej['IndepYear'].dropna().count())

Numero de elementos nulos (IndepYear): 14

dropna tiene dos parámetros que modifican su funcionamiento:
 -- `axis`: para especificar si los valores nulos se buscarán por fila (`0`) o columna (`1`)

 -- `how`: Si borra el elemento con un solo valor nulo (`'any'`) o todos los elementos deben de ser nulos (`'all'`)

In [ ]:
#Borra cualquier fila que tenga un valor nulo
print("\n\n\nAxis=0, How=Any:\n",Ej.dropna(axis=0, how='any'))

Axis=0, How=Any:
                       Name  IndepYear  Population       GNP    GNPOld
Code
AGO                 Angola     1975.0    12878000    6648.0    7984.0
ARE   United Arab Emirates     1971.0     2441000       0.0   36846.0
ARG              Argentina     1816.0    37032000  340238.0  323310.0
ARM                Armenia     1991.0     3520000    1813.0    1627.0
ATG    Antigua and Barbuda     1981.0       68000     612.0     584.0
AUS              Australia     1901.0           0  351182.0  392911.0
AUT                Austria     1918.0     8091800       0.0  206025.0
AZE             Azerbaijan     1991.0     7734000    4127.0    4100.0
BDI                Burundi     1962.0     6695000     903.0     982.0
BEL                Belgium     1830.0    10239000  249704.0  243948.0
BEN                  Benin     1960.0     6097000    2357.0    2141.0

In [ ]:
#Se cambian los valores a NaN de una fila y columna para ver el funcionamiento de how='all'
from numpy import nan
Ej['Name']=nan
Ej.loc['AND']=nan
Ej

      Name  IndepYear  Population       GNP    GNPOld
Code
ABW    NaN        NaN    103000.0     828.0     793.0
AFG    NaN     1919.0  22720000.0    5976.0       NaN
AGO    NaN     1975.0  12878000.0    6648.0    7984.0
AIA    NaN        NaN      8000.0      63.2       NaN
ALB    NaN     1912.0   3401200.0    3205.0    2500.0
AND    NaN        NaN         NaN       NaN       NaN
ANT    NaN        NaN    217000.0    1941.0       NaN
ARE    NaN     1971.0   2441000.0       0.0   36846.0
ARG    NaN     1816.0  37032000.0  340238.0  323310.0
ARM    NaN     1991.0   3520000.0    1813.0    1627.0
ASM    NaN        NaN     68000.0     334.0       NaN
ATA    NaN        NaN         0.0       0.0       NaN
ATF    NaN        NaN         0.0       0.0       NaN
ATG    NaN     1981.0     68000.0     612.0     584.0
AUS    NaN     1901.0         0.0  351182.0  392911.0
AUT    NaN     1918.0   8091800.0       0.0  206025.0
AZE    NaN     1991.0   7734000.0    4127.0    4100.0
BDI    NaN     1962.0   6695000.0     903.0     982.0
BEL    NaN     1830.0  10239000.0  249704.0  243948.0
BEN    NaN     1960.0   6097000.0    2357.0    2141.0

In [ ]:
#Borra cualquier fila donde TODOS sus valores sean nulos
print("\n\n\nAxis=0, How=all:\n",Ej.dropna(axis=0, how='all'))

Axis=0, How=all:
       Name  IndepYear  Population       GNP    GNPOld
Code
ABW    NaN        NaN    103000.0     828.0     793.0
AFG    NaN     1919.0  22720000.0    5976.0       NaN
AGO    NaN     1975.0  12878000.0    6648.0    7984.0
AIA    NaN        NaN      8000.0      63.2       NaN
ALB    NaN     1912.0   3401200.0    3205.0    2500.0
ANT    NaN        NaN    217000.0    1941.0       NaN
ARE    NaN     1971.0   2441000.0       0.0   36846.0
ARG    NaN     1816.0  37032000.0  340238.0  323310.0
ARM    NaN     1991.0   3520000.0    1813.0    1627.0
ASM    NaN        NaN     68000.0     334.0       NaN
ATA    NaN        NaN         0.0       0.0       NaN
ATF    NaN        NaN         0.0       0.0       NaN
ATG    NaN     1981.0     68000.0     612.0     584.0
AUS    NaN     1901.0         0.0  351182.0  392911.0
AUT    NaN     1918.0   8091800.0       0.0  206025.0
AZE    NaN     1991.0   7734000.0    4127.0    4100.0
BDI    NaN     1962.0   6695000.0     903.0     982.0
BEL    NaN     1830.0  10239000.0  249704.0  243948.0
BEN    NaN     1960.0   6097000.0    2357.0    2141.0

In [ ]:
#Borra cualquier columna donde TODOS sus valores sean nulos
print("\n\n\nAxis=1, How=all:\n",Ej.dropna(axis=1, how='all'))

Axis=1, How=all:
       IndepYear  Population       GNP    GNPOld
Code
ABW         NaN    103000.0     828.0     793.0
AFG      1919.0  22720000.0    5976.0       NaN
AGO      1975.0  12878000.0    6648.0    7984.0
AIA         NaN      8000.0      63.2       NaN
ALB      1912.0   3401200.0    3205.0    2500.0
AND         NaN         NaN       NaN       NaN
ANT         NaN    217000.0    1941.0       NaN
ARE      1971.0   2441000.0       0.0   36846.0
ARG      1816.0  37032000.0  340238.0  323310.0
ARM      1991.0   3520000.0    1813.0    1627.0
ASM         NaN     68000.0     334.0       NaN
ATA         NaN         0.0       0.0       NaN
ATF         NaN         0.0       0.0       NaN
ATG      1981.0     68000.0     612.0     584.0
AUS      1901.0         0.0  351182.0  392911.0
AUT      1918.0   8091800.0       0.0  206025.0
AZE      1991.0   7734000.0    4127.0    4100.0
BDI      1962.0   6695000.0     903.0     982.0
BEL      1830.0  10239000.0  249704.0  243948.0
BEN      1960.0   6097000.0    2357.0    2141.0

##Modificar el valor de los datos nulos
Se utiliza la función `fillna` para reemplazar los valores nulos por un dato específico

In [ ]:
Ej=pd.read_csv('Country2.csv', index_col='Code', nrows=20)
Ej=Ej.drop(['SurfaceArea','LifeExpectancy','Continent','Region','LocalName','GovernmentForm','Capital'], axis=1)
Ej.head()

             Name  IndepYear  Population     GNP  GNPOld
Code
ABW         Aruba        NaN      103000   828.0   793.0
AFG   Afghanistan     1919.0    22720000  5976.0     NaN
AGO        Angola     1975.0    12878000  6648.0  7984.0
AIA           NaN        NaN        8000    63.2     NaN
ALB           NaN     1912.0     3401200  3205.0  2500.0

In [ ]:
Ej.fillna('--',inplace=True)
Ej

<ipython-input-56-e0556b223ef8>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '--' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  Ej.fillna('--',inplace=True)

                             Name IndepYear  Population       GNP    GNPOld
Code
ABW                         Aruba        --      103000     828.0     793.0
AFG                   Afghanistan    1919.0    22720000    5976.0        --
AGO                        Angola    1975.0    12878000    6648.0    7984.0
AIA                            --        --        8000      63.2        --
ALB                            --    1912.0     3401200    3205.0    2500.0
AND                       Andorra    1278.0           0    1630.0        --
ANT          Netherlands Antilles        --      217000    1941.0        --
ARE          United Arab Emirates    1971.0     2441000       0.0   36846.0
ARG                     Argentina    1816.0    37032000  340238.0  323310.0
ARM                       Armenia    1991.0     3520000    1813.0    1627.0
ASM                American Samoa        --       68000     334.0        --
ATA                    Antarctica        --           0       0.0        --
ATF   French Southern territories        --           0       0.0        --
ATG           Antigua and Barbuda    1981.0       68000     612.0     584.0
AUS                     Australia    1901.0           0  351182.0  392911.0
AUT                       Austria    1918.0     8091800       0.0  206025.0
AZE                    Azerbaijan    1991.0     7734000    4127.0    4100.0
BDI                       Burundi    1962.0     6695000     903.0     982.0
BEL                       Belgium    1830.0    10239000  249704.0  243948.0
BEN                         Benin    1960.0     6097000    2357.0    2141.0

In [ ]:
Ej.fillna({'Name':'ND','IndepYear':int(Ej['IndepYear'].mean()),'GNPOld':int(Ej['GNPOld'].mean())})

TypeError: can only concatenate str (not "float") to str

In [ ]:
#Para reemplazar los datos (0) por otro valor
print("Reemplaza todos los 0's por 9999\n",Ej.replace(0,9999))

Reemplaza todos los 0's por 9999
                              Name IndepYear  Population       GNP    GNPOld
Code
ABW                         Aruba        --      103000     828.0     793.0
AFG                   Afghanistan    1919.0    22720000    5976.0        --
AGO                        Angola    1975.0    12878000    6648.0    7984.0
AIA                            --        --        8000      63.2        --
ALB                            --    1912.0     3401200    3205.0    2500.0
AND                       Andorra    1278.0        9999    1630.0        --
ANT          Netherlands Antilles        --      217000    1941.0        --
ARE          United Arab Emirates    1971.0     2441000    9999.0   36846.0
ARG                     Argentina    1816.0    37032000  340238.0  323310.0
ARM                       Armenia    1991.0     3520000    1813.0    1627.0
ASM                American Samoa        --       68000     334.0        --
ATA                    Antarctica        --        9999    9999.0        --
ATF   French Southern territories        --        9999    9999.0        --
ATG           Antigua and Barbuda    1981.0       68000     612.0     584.0
AUS                     Australia    1901.0        9999  351182.0  392911.0
AUT                       Austria    1918.0     8091800    9999.0  206025.0
AZE                    Azerbaijan    1991.0     7734000    4127.0    4100.0
BDI                       Burundi    1962.0     6695000     903.0     982.0
BEL                       Belgium    1830.0    10239000  249704.0  243948.0
BEN                         Benin    1960.0     6097000    2357.0    2141.0

##Ejercicios
Lee el archivo "ParaEjercicios.csv" y realiza lo siguiente:

In [ ]:
import pandas as pd
from pandas import DataFrame
Ejemplo=pd.read_csv("ParaEjercicios.csv")
Ejemplo.head()

,Id,Nombre,Categoria,Existencia,PrecioCompra,PrecioVenta
0,DFG,Lapiz,Escritura,40.0,5.0,1500.00
1,ESC,Borrador,Pizarron,60.0,NaN,22.60
2,FBD,Goma,Escritura,NaN,10.0,12.40
3,QWE,Marcador Permanente Negro,Escritura,45.0,35.0,42.00
4,RVF,Corrector,Escritura,39.0,18.0,19.44

-- Visualiza las filas que tengan dato nulo en Precio de compra. Guarda las claves de estas filas en una lista

In [ ]:
#Ejemplo[Ejemplo.isnull().any(axis=1)]

In [ ]:
IndicesBorrar=Ejemplo[Ejemplo['PrecioCompra'].isnull()].index.to_list()
IndicesBorrar

[1, 5, 10, 13, 20]

Rellena el dato perdido de precio de compra con el precio promedio de esta columna

In [ ]:
promedio=Ejemplo['PrecioCompra'].mean()

In [ ]:
Ejemplo['PrecioCompra'].fillna(Ejemplo['PrecioCompra'].mean(),inplace=True)
Ejemplo

,Id,Nombre,Categoria,Existencia,PrecioCompra,PrecioVenta
0,DFG,Lapiz,Escritura,40.0,5.000000,1500.00
1,ESC,Borrador,Pizarron,60.0,31.363636,22.60
2,FBD,Goma,Escritura,NaN,10.000000,12.40
3,QWE,Marcador Permanente Negro,Escritura,45.0,35.000000,42.00
4,RVF,Corrector,Escritura,39.0,18.000000,19.44
5,UJM,Boligrafo Azul,Escritura,46.0,31.363636,5.55
6,IOP,Boligrafo Rojo,Escritura,75.0,5.000000,5.90
7,LJH,Marcador Permanente Azul,Escritura,36.0,35.000000,NaN
8,GFT,Marcador Permanente Rojo,Escritura,NaN,35.000000,40.25
9,RDF,Sacapuntas,Escritura,45.0,20.000000,23.40
10,TGS,Juego De Geometria,Dibujo,65.0,31.363636,69.30
11,TRE,Lapiz De Dibujo H2,Dibujo,32.0,23.000000,29.44
12,VSD,Regla 60Cm,Dibujo,48.0,30.000000,33.30
13,ASD,Colores Prismacolor,Dibujo,76.0,31.363636,163.50
14,AQW,Colores Fantasy,Dibujo,NaN,130.000000,159.90
15,CDE,Hoja Blanca Carta,Papel,36.0,40.000000,49.60
16,SDF,Hoja Blanca Oficio,Papel,29.0,50.000000,53.00
17,JHG,Portaminas,Escritura,64.0,76.000000,95.76
18,FRD,Tijeras,Dibujo,75.0,45.000000,47.70
19,RTD,Plumon Rojo,Pizarron,NaN,28.000000,36.12
20,TYH,Plumon Azul,Pizarron,45.0,31.363636,32.20
21,TRD,Plumon Negro,Pizarron,47.0,28.000000,36.40
22,TRO,Calcomanias,Otro,100.0,10.000000,12.30
23,HYU,Clips,Otro,70.0,16.000000,NaN
24,IOM,Boligrafo Rojo,Escritura,75.0,5.000000,5.90
25,VSS,Regla 60Cm,Dibujo,48.0,30.000000,33.30
26,HYH,Clips,Otro,70.0,16.000000,20.00

Muestra SOLO los datos modificados

In [ ]:
Ejemplo.loc[IndicesBorrar]

     Id               Nombre  Categoria  Existencia  PrecioCompra  PrecioVenta
1   ESC             Borrador   Pizarron        60.0     31.363636        22.60
5   UJM       Boligrafo Azul  Escritura        46.0     31.363636         5.55
10  TGS   Juego De Geometria     Dibujo        65.0     31.363636        69.30
13  ASD  Colores Prismacolor     Dibujo        76.0     31.363636       163.50
20  TYH          Plumon Azul   Pizarron        45.0     31.363636        32.20

Elimina las filas que tengan algún dato nulo en la columna de Existencia.
Imprime los nombres de los productos eliminados

In [ ]:
print('Productos eliminados:',Ejemplo[Ejemplo['Existencia'].isnull()]['Nombre'].to_list())
Ejemplo.dropna(subset=['Existencia'],inplace=True)
Ejemplo

Productos eliminados: ['Goma', 'Marcador Permanente Rojo', 'Colores Fantasy', 'Plumon Rojo']

,Id,Nombre,Categoria,Existencia,PrecioCompra,PrecioVenta
0,DFG,Lapiz,Escritura,40.0,5.000000,1500.00
1,ESC,Borrador,Pizarron,60.0,31.363636,22.60
3,QWE,Marcador Permanente Negro,Escritura,45.0,35.000000,42.00
4,RVF,Corrector,Escritura,39.0,18.000000,19.44
5,UJM,Boligrafo Azul,Escritura,46.0,31.363636,5.55
6,IOP,Boligrafo Rojo,Escritura,75.0,5.000000,5.90
7,LJH,Marcador Permanente Azul,Escritura,36.0,35.000000,NaN
9,RDF,Sacapuntas,Escritura,45.0,20.000000,23.40
10,TGS,Juego De Geometria,Dibujo,65.0,31.363636,69.30
11,TRE,Lapiz De Dibujo H2,Dibujo,32.0,23.000000,29.44
12,VSD,Regla 60Cm,Dibujo,48.0,30.000000,33.30
13,ASD,Colores Prismacolor,Dibujo,76.0,31.363636,163.50
15,CDE,Hoja Blanca Carta,Papel,36.0,40.000000,49.60
16,SDF,Hoja Blanca Oficio,Papel,29.0,50.000000,53.00
17,JHG,Portaminas,Escritura,64.0,76.000000,95.76
18,FRD,Tijeras,Dibujo,75.0,45.000000,47.70
20,TYH,Plumon Azul,Pizarron,45.0,31.363636,32.20
21,TRD,Plumon Negro,Pizarron,47.0,28.000000,36.40
22,TRO,Calcomanias,Otro,100.0,10.000000,12.30
23,HYU,Clips,Otro,70.0,16.000000,NaN
24,IOM,Boligrafo Rojo,Escritura,75.0,5.000000,5.90
25,VSS,Regla 60Cm,Dibujo,48.0,30.000000,33.30
26,HYH,Clips,Otro,70.0,16.000000,20.00