# Act 2-3. Consultas y lectura de archivos.ipynb
Diego Soto
Cesar Rivera A01567012
Julio Sotero

In [ ]:
import pandas as pd
from pandas import DataFrame

 **(10 puntos) Generar Frames
Genera un frame por archivo**

In [ ]:
Frame_Ciudades=pd.read_html('Ciudades.html',header=0, index_col=0,encoding='utf-8')
#al leer un archivo html se retorna una lista de frames
Frame_Ciudades[0]

                Name CountryCode  Population
ID
1              Kabul         AFG     1780000
2           Qandahar         AFG      237500
3              Herat         AFG      186800
4     Mazar-e-Sharif         AFG      127800
5          Amsterdam         NLD      731200
...              ...         ...         ...
4075      Khan Yunis         PSE      123175
4076          Hebron         PSE      119401
4077        Jabaliya         PSE      113901
4078          Nablus         PSE      100231
4079           Rafah         PSE       92020

[4079 rows x 3 columns]

In [ ]:
Frame_Paises= pd.read_json('Paises.json', orient='index')
Frame_Paises.column=['Name','CountryCode','Population']
Frame_Paises.head()

<ipython-input-70-f6f394957a32>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  Frame_Paises.column=['Name','CountryCode','Population']

,Name,Continent,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,Capital
ABW,Aruba,North America,193.0,NaN,103000,78.4,828.0,129.0
AFG,Afghanistan,Asia,652090.0,1919.0,22720000,45.9,5976.0,1.0
AGO,Angola,Africa,1246700.0,1975.0,12878000,38.3,6648.0,56.0
AIA,Anguilla,North America,96.0,NaN,8000,76.1,63.2,62.0
ALB,Albania,Europe,28748.0,1912.0,3401200,71.6,3205.0,34.0

**(10 puntos) Revisar estructura:
Realiza un análisis de la estructura a través de los atributos principales del dataframe (shape,
columns, index, dtypes).
Agrega al menos 5 ejemplos de estos comandos en las diferentes tablas, especificando en
comentarios lo que estás**

In [ ]:
print("atributos html: ")
print("\n")
print("1.-html shape: ", Frame_Ciudades[0].shape) #número de filas y columnas
print("\n")
print("2.-html columns: ", Frame_Ciudades[0].columns) #retorna una serie
print("\n")
print("3.-htmL lindex: ", Frame_Ciudades[0].index) #muestra los indices de la serie
print("\n")
print("4.-html types: ", Frame_Ciudades[0].dtypes) #retorna el tipo de dato de la serie
print("\n")
print("5.-", Frame_Ciudades[0].info()) #muestra la información del frame

atributos html:


1.-html shape:  (4079, 3)


2.-html columns:  Index(['Name', 'CountryCode', 'Population'], dtype='object')


3.-htmL lindex:  Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       4070, 4071, 4072, 4073, 4074, 4075, 4076, 4077, 4078, 4079],
      dtype='int64', name='ID', length=4079)


4.-html types:  Name           object
CountryCode    object
Population      int64
dtype: object


<class 'pandas.core.frame.DataFrame'>
Index: 4079 entries, 1 to 4079
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4079 non-null   object
 1   CountryCode  4079 non-null   object
 2   Population   4079 non-null   int64
dtypes: int64(1), object(2)
memory usage: 127.5+ KB
5.- None

In [ ]:
print("atributos json: ")
print("\n")
print("1.-json shape: ", Frame_Paises.shape) #número de filas y columnas
print("\n")
print("2.-json columns: ", Frame_Paises.columns) #retorna una serie
print("\n")
print("3.-json lindex: ", Frame_Paises.index) #muestra los indices de la serie
print("\n")
print("4.-json types: ", Frame_Paises.dtypes) #retorna el tipo de dato de la serie
print("\n")
print("5.-", Frame_Paises['Name']) #muestra la columna 'Name'

atributos json:


1.-json shape:  (239, 8)


2.-json columns:  Index(['Name', 'Continent', 'SurfaceArea', 'IndepYear', 'Population',
       'LifeExpectancy', 'GNP', 'Capital'],
      dtype='object')


3.-json lindex:  Index(['ABW', 'AFG', 'AGO', 'AIA', 'ALB', 'AND', 'ANT', 'ARE', 'ARG', 'ARM',
       ...
       'VIR', 'VNM', 'VUT', 'WLF', 'WSM', 'YEM', 'YUG', 'ZAF', 'ZMB', 'ZWE'],
      dtype='object', length=239)


4.-json types:  Name               object
Continent          object
SurfaceArea       float64
IndepYear         float64
Population          int64
LifeExpectancy    float64
GNP               float64
Capital           float64
dtype: object


5.- ABW           Aruba
AFG     Afghanistan
AGO          Angola
AIA        Anguilla
ALB         Albania
           ...
YEM           Yemen
YUG      Yugoslavia
ZAF    South Africa
ZMB          Zambia
ZWE        Zimbabwe
Name: Name, Length: 239, dtype: object

(10 puntos) Explorar contenido:
Explora el contenido con los algunos de los métodos de utilidad estudiados (head(), tail(),
sort_values(), sort_index(), nunique(), duplicated()

In [ ]:
print("html primeras 5 filas:\n", Frame_Ciudades.head())  #primeras filas del archivo de html (ciudades)
print("\n")
print("json ultimas 5 filas:\n", Frame_Paises.tail()) #ultimas filas del archivo de jason (paises)
print("\n")
print("json ordenado por población:\n", Frame_Paises.head())
print("\n")
Frame_Ciudades = Frame_Ciudades.sort_index() #ordenar archivo html (ciudades) por clave
print("\n")
print("html ordenado por índice:\n", Frame_Ciudades.head())
print("\n")
print("json valores únicos por columna:\n", Frame_Paises.nunique()) #contamos valores únicos en archivo json (paises)
print("\n")
print("html filas duplicadas:\n", Frame_Ciudades.duplicated().sum())  # Muestra el número de filas duplicadas
print("\n")
print("json filas duplicadas:\n", Frame_Paises.duplicated().sum()) #muestra el número de filas duplicadas

html primeras 5 filas:
               Name CountryCode  Population
ID
1            Kabul         AFG     1780000
2         Qandahar         AFG      237500
3            Herat         AFG      186800
4   Mazar-e-Sharif         AFG      127800
5        Amsterdam         NLD      731200


json ultimas 5 filas:
                                              Name   Continent  SurfaceArea  \
SGS  South Georgia and the South Sandwich Islands  Antarctica       3903.0
ATA                                    Antarctica  Antarctica   13120000.0
UMI          United States Minor Outlying Islands     Oceania         16.0
IOT                British Indian Ocean Territory      Africa         78.0
ATF                   French Southern territories  Antarctica       7780.0

     IndepYear  Population  LifeExpectancy  GNP  Capital
SGS        NaN           0             NaN  0.0      NaN
ATA        NaN           0             NaN  0.0      NaN
UMI        NaN           0             NaN  0.0      NaN
IOT        NaN           0             NaN  0.0      NaN
ATF        NaN           0             NaN  0.0      NaN


json ordenado por población:
               Name      Continent  SurfaceArea  IndepYear  Population  \
CHN          China           Asia    9572900.0    -1523.0  1277558000
IND          India           Asia    3287263.0     1947.0  1013662000
USA  United States  North America    9363520.0     1776.0   278357000
IDN      Indonesia           Asia    1904569.0     1945.0   212107000
BRA         Brazil  South America    8547403.0     1822.0   170115000

     LifeExpectancy        GNP  Capital
CHN            71.4   982268.0   1891.0
IND            62.5   447114.0   1109.0
USA            77.1  8510700.0   3813.0
IDN             NaN    84982.0    939.0
BRA            62.9   776739.0    211.0




html ordenado por índice:
               Name CountryCode  Population
ID
1            Kabul         AFG     1780000
2         Qandahar         AFG      237500
3            Herat         AFG      186800
4   Mazar-e-Sharif         AFG      127800
5        Amsterdam         NLD      731200


json valores únicos por columna:
 Name              238
Continent           7
SurfaceArea       238
IndepYear          88
Population        226
LifeExpectancy    159
GNP               214
Capital           232
dtype: int64


html filas duplicadas:
 0


json filas duplicadas:
 0

# **(30 puntos) Tratamiento de datos:**
En el frame de países realiza lo siguiente, recuerda ir guardando los cambios en el frame, no solo
imprimir en pantalla
1. Reemplaza los datos nulos de la columna de expectativa de vida por el promedio de esta
columna, y los valores nulos de la columna de año de independencia por 1990

In [ ]:
Frame_Paises.fillna({'LifeExpectancy':Frame_Paises['LifeExpectancy'].mean(),'IndepYear':1990},inplace=True)
Frame_Paises.head()

,Name,Continent,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,Capital
ABW,Aruba,North America,193.0,1990.0,103000,78.4,828.0,129.0
AFG,Afghanistan,Asia,652090.0,1919.0,22720000,45.9,5976.0,1.0
AGO,Angola,Africa,1246700.0,1975.0,12878000,38.3,6648.0,56.0
AIA,Anguilla,North America,96.0,1990.0,8000,76.1,63.2,62.0
ALB,Albania,Europe,28748.0,1912.0,3401200,71.6,3205.0,34.0

2. Borra la columna ‘GNP’

In [ ]:
Frame_Paises.drop(columns='GNP',inplace=True)
Frame_Paises.head()

,Name,Continent,SurfaceArea,IndepYear,Population,LifeExpectancy,Capital
ABW,Aruba,North America,193.0,1990.0,103000,78.4,129.0
AFG,Afghanistan,Asia,652090.0,1919.0,22720000,45.9,1.0
AGO,Angola,Africa,1246700.0,1975.0,12878000,38.3,56.0
AIA,Anguilla,North America,96.0,1990.0,8000,76.1,62.0
ALB,Albania,Europe,28748.0,1912.0,3401200,71.6,34.0

3. Guarda los países del frame en un archivo CSV llamado “Países.csv”

In [ ]:
Frame_Paises.to_csv('Países.csv')

4. Imprime en pantalla el total de países registrados por continente

In [ ]:
Paises_NorteAmerica=Frame_Paises['Name'][Frame_Paises['Continent']=='North America']
Paises_SurAmerica=Frame_Paises['Name'][Frame_Paises['Continent']== 'South America']
Paises_America=Paises_NorteAmerica+Paises_SurAmerica
Paises_Africa=Frame_Paises['Name'][Frame_Paises['Continent']=='Africa']
Paises_Asia=Frame_Paises['Name'][Frame_Paises['Continent']== 'Asia']
Paises_Oceania=Frame_Paises['Name'][Frame_Paises['Continent']== 'Oceania']
Paises_Asia=Frame_Paises['Name'][Frame_Paises['Continent']== 'Europe']
Paises_Antartica=Frame_Paises['Name'][Frame_Paises['Continent']== 'Antartica']

In [ ]:
print("\nCantidad de paises en AMERICA: ",len(Paises_America))
print("\nCantidad de paises en AFRICA: ",len(Paises_Africa))
print("\nCantidad de paises en ASIA: ",len(Paises_Asia))
print("\nCantidad de paises en OCEANIA: ",len(Paises_Oceania))
print("\nCantidad de paises en ANTARTICA: ",len(Paises_Antartica))

Cantidad de paises en AMERICA:  51

Cantidad de paises en AFRICA:  58

Cantidad de paises en ASIA:  46

Cantidad de paises en OCEANIA:  28

Cantidad de paises en ANTARTICA:  0